const menuToggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');if(menuToggle&&nav){menuToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open?'true':'false')})}const revealEls=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')})},{threshold:.12});revealEls.forEach(el=>observer.observe(el));const feedback=document.getElementById('feedback');const vcard=`BEGIN:VCARD
VERSION:3.0
N:Badila;Mamly;;;
FN:Mamly Badila
TITLE:Conformité - Sécurité financière - Gestion de projets
TEL;TYPE=CELL:+242064773223
EMAIL;TYPE=INTERNET:mamlyb93@gmail.com
ADR;TYPE=WORK:;;Brazzaville;;;République du Congo
NOTE:Structurer la confiance, sécuriser la croissance.
END:VCARD`;document.getElementById('saveContact')?.addEventListener('click',()=>{const blob=new Blob([vcard],{type:'text/vcard;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Mamly-Badila.vcf';a.click();URL.revokeObjectURL(url);if(feedback)feedback.textContent='Le contact a été préparé pour téléchargement.'});document.getElementById('copyLink')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(window.location.href);if(feedback)feedback.textContent='Lien copié.'}catch{if(feedback)feedback.textContent='Copie impossible sur ce navigateur.'}});document.getElementById('shareCard')?.addEventListener('click',async()=>{if(navigator.share){await navigator.share({title:'Carte professionnelle de Mamly Badila',text:'Découvrez la carte professionnelle de Mamly Badila.',url:window.location.href})}else if(feedback){feedback.textContent='Le partage natif n’est pas disponible ici. Utilise « Copier le lien ».'}});